<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>6.0.0</Version>
		<Authors>UIOMatic</Authors>
		<Description>UIOMatic Core - Auto generate an integrated crud UI in Umbraco for a db table based on a npoco poco</Description>
		<PackageTags>umbraco;uiomatic</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/UIOMatic/UIOMatic</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
	</ItemGroup>

</Project>
